# PostgreSQL. Versions 9.3 and up are supported.
#
# Configure Using Gemfile
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: capstone_backend_development
  # Default setup for local development
  #host: localhost
  #port: 5432

test:
  <<: *default
  database: capstone_backend_test

production:
  <<: *default
  database: capstone_backend_production
  username: <%= ENV["CAPSTONE_BACKEND_DATABASE_USERNAME"] %>
  password: <%= ENV["CAPSTONE_BACKEND_DATABASE_PASSWORD"] %>
  host: <%= ENV["CAPSTONE_BACKEND_DATABASE_HOST"] %>
  port: <%= ENV.fetch("CAPSTONE_BACKEND_DATABASE_PORT") { 5432 } %>
  # Optional: Specify SSL mode for secure connection
  # sslmode: require
